language: php

php:
  - 5.4
  - 5.5
  - 5.6

sudo: false

env:
  - DB=sqlite db_class='Cake\Database\Driver\Sqlite' db_dsn='sqlite::memory:'

matrix:
  allow_failures:
    - php: hhvm-nightly
  fast_finish: true
  include:
    - php: 5.4
      env: PHPCS=1
    - php: hhvm-nightly
      env: HHVM=1 DB=sqlite db_class='Cake\Database\Driver\Sqlite' db_dsn='sqlite::memory:'

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - phpenv rehash
  - set +H

script:
  - sh -c "if [ '$PHPCS' != '1' ]; then phpunit; fi"
  - sh -c "if [ '$PHPCS' = '1' ]; then vendor/bin/phpcs -p -n --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP . --ignore=vendor; fi"

notifications:
  email: false
